### ISSUE TITLE
Add a command that makes it so the host controls the game

### ISSUE THREAD

**Issue by Hunter589** [pedrofracassi/amongcord#10]

**Comment by Hunter589** [comment]
Add a command like ,host that makes it so that the host gets a private sync code and nobody else can control it

**Comment by tronage** [comment]
The current workaround for this (that I use) is I create a special amongcord text channel that has @everybody with no read permissions (so nobody can see it) but then the amongcord roll has explicit read permissions, so the bot can be in there.  This also requires that you set the amongcord roll to have no read rites in your other text chat channels.  Since you have a "private" channel for just you and the bot, only you can control it...  The key is making sure it is ONLY in that one channel that others don't have access to.
However, the issues arise that people can't join themselves, requiring the new forcejoin command (or joinall).
Ideally, though I agree that the bot should only listen to someone else who has muting power otherwise the bot could be abused to mute people (by someone who doesn't natively have mute power).  Which I believe the developer is working on (fingers crossed).

**Comment by pedrofracassi** [comment]
> Which I believe the developer is working on (fingers crossed).

Yes I am!

**Comment by pedrofracassi** [comment]
Done!
